CREATE DATABASE INVENTARIO

GO

USE INVENTARIO

GO

CREATE TABLE PRODUCTOS(
    Clave VARCHAR(6) PRIMARY KEY NOT NULL,
    Nombre VARCHAR(MAX) NOT NULL,
    Precio DECIMAL(18,2) NOT NULL
)

GO

CREATE TABLE SUCURSALES(
    Clave VARCHAR(3) PRIMARY KEY NOT NULL,
    Nombre VARCHAR(MAX) NOT NULL
)

GO

CREATE TABLE EXISTENCIAS(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Sucursal VARCHAR(3) NOT NULL,
    Producto VARCHAR(6) NOT NULL,
    Cantidad INT NOT NULL
)

GO

ALTER TABLE EXISTENCIAS
    ADD CONSTRAINT FK_SUCURSAL FOREIGN KEY (Sucursal)
    REFERENCES SUCURSALES (Clave)

GO

ALTER TABLE EXISTENCIAS
    ADD CONSTRAINT FK_PRODUCTO FOREIGN KEY (Producto)
    REFERENCES PRODUCTOS (Clave)

GO

INSERT INTO PRODUCTOS VALUES 
('100010','Café Legal',7.0),
('100011','Chocolate Abuelita',15.0),
('100012','Bonafina',12.0)

GO

INSERT INTO SUCURSALES VALUES 
('AAA','Sucursal A'),
('BBB','Sucursal B')

GO

INSERT INTO EXISTENCIAS VALUES
('AAA','100010',5),
('AAA','100011',6),
('AAA','100012',1),
('BBB','100010',8),
('BBB','100011',4),
('BBB','100012',2)

GO
